package com.microsoft.azure.sdk.iot.digitaltwin.device;

public enum DigitalTwinClientResult {
    DIGITALTWIN_CLIENT_OK,
    DIGITALTWIN_CLIENT_ERROR_INVALID_ARG,
    DIGITALTWIN_CLIENT_ERROR_OUT_OF_MEMORY,
    DIGITALTWIN_CLIENT_ERROR_REGISTRATION_PENDING,
    DIGITALTWIN_CLIENT_ERROR_INTERFACE_ALREADY_REGISTERED,
    DIGITALTWIN_CLIENT_ERROR_INTERFACE_NOT_REGISTERED,
    DIGITALTWIN_CLIENT_ERROR_INTERFACE_UNREGISTERING,
    DIGITALTWIN_CLIENT_ERROR_COMMAND_NOT_PRESENT,
    DIGITALTWIN_CLIENT_ERROR_SHUTTING_DOWN,
    DIGITALTWIN_CLIENT_ERROR_TIMEOUT,
    DIGITALTWIN_CLIENT_ERROR_HANDLE_DESTROYED,
    DIGITALTWIN_CLIENT_ERROR_ACCESS_DENIED,
    DIGITALTWIN_CLIENT_ERROR_CALLBACK_ALREADY_REGISTERED,
    DIGITALTWIN_CLIENT_ERROR
}
