package com.microsoft.azure.sdk.iot.digitaltwin.device;

public enum DigitalTwinClientResult {
    DIGITALTWIN_CLIENT_OK,
    DIGITALTWIN_CLIENT_ERROR_REGISTRATION_PENDING,
    DIGITALTWIN_CLIENT_ERROR_INTERFACE_ALREADY_REGISTERED,
    DIGITALTWIN_CLIENT_ERROR_INTERFACE_NOT_REGISTERED,
    DIGITALTWIN_CLIENT_ERROR
}
