/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.sdk.iot.provisioning.service.models;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Bulk operation.
 */
public class BulkEnrollmentOperation {
    /**
     * Enrollment items.
     */
    @JsonProperty(value = "enrollments", required = true)
    private List<IndividualEnrollment> enrollments;

    /**
     * Operation mode. Possible values include: 'create', 'update',
     * 'updateIfMatchETag', 'delete'.
     */
    @JsonProperty(value = "mode", required = true)
    private String mode;

    /**
     * Get enrollment items.
     *
     * @return the enrollments value
     */
    public List<IndividualEnrollment> enrollments() {
        return this.enrollments;
    }

    /**
     * Set enrollment items.
     *
     * @param enrollments the enrollments value to set
     * @return the BulkEnrollmentOperation object itself.
     */
    public BulkEnrollmentOperation withEnrollments(List<IndividualEnrollment> enrollments) {
        this.enrollments = enrollments;
        return this;
    }

    /**
     * Get operation mode. Possible values include: 'create', 'update', 'updateIfMatchETag', 'delete'.
     *
     * @return the mode value
     */
    public String mode() {
        return this.mode;
    }

    /**
     * Set operation mode. Possible values include: 'create', 'update', 'updateIfMatchETag', 'delete'.
     *
     * @param mode the mode value to set
     * @return the BulkEnrollmentOperation object itself.
     */
    public BulkEnrollmentOperation withMode(String mode) {
        this.mode = mode;
        return this;
    }

}
