/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.sdk.iot.provisioning.service.models;

import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Device registration state.
 */
public class DeviceRegistrationState {
    /**
     * The registration ID is alphanumeric, lowercase, and may contain hyphens.
     */
    @JsonProperty(value = "registrationId", access = JsonProperty.Access.WRITE_ONLY)
    private String registrationId;

    /**
     * Registration create date time (in UTC).
     */
    @JsonProperty(value = "createdDateTimeUtc", access = JsonProperty.Access.WRITE_ONLY)
    private DateTime createdDateTimeUtc;

    /**
     * Assigned Azure IoT Hub.
     */
    @JsonProperty(value = "assignedHub", access = JsonProperty.Access.WRITE_ONLY)
    private String assignedHub;

    /**
     * Device ID.
     */
    @JsonProperty(value = "deviceId", access = JsonProperty.Access.WRITE_ONLY)
    private String deviceId;

    /**
     * Enrollment status. Possible values include: 'unassigned', 'assigning',
     * 'assigned', 'failed', 'disabled'.
     */
    @JsonProperty(value = "status", access = JsonProperty.Access.WRITE_ONLY)
    private String status;

    /**
     * Substatus for 'Assigned' devices. Possible values include -
     * 'initialAssignment': Device has been assigned to an IoT hub for the
     * first time, 'deviceDataMigrated': Device has been assigned to a
     * different IoT hub and its device data was migrated from the previously
     * assigned IoT hub. Device data was removed from the previously assigned
     * IoT hub, 'deviceDataReset':  Device has been assigned to a different IoT
     * hub and its device data was populated from the initial state stored in
     * the enrollment. Device data was removed from the previously assigned IoT
     * hub. Possible values include: 'initialAssignment', 'deviceDataMigrated',
     * 'deviceDataReset'.
     */
    @JsonProperty(value = "substatus", access = JsonProperty.Access.WRITE_ONLY)
    private String substatus;

    /**
     * Error code.
     */
    @JsonProperty(value = "errorCode", access = JsonProperty.Access.WRITE_ONLY)
    private Integer errorCode;

    /**
     * Error message.
     */
    @JsonProperty(value = "errorMessage", access = JsonProperty.Access.WRITE_ONLY)
    private String errorMessage;

    /**
     * Last updated date time (in UTC).
     */
    @JsonProperty(value = "lastUpdatedDateTimeUtc", access = JsonProperty.Access.WRITE_ONLY)
    private DateTime lastUpdatedDateTimeUtc;

    /**
     * The entity tag associated with the resource.
     */
    @JsonProperty(value = "etag", access = JsonProperty.Access.WRITE_ONLY)
    private String etag;

    /**
     * Get the registration ID is alphanumeric, lowercase, and may contain hyphens.
     *
     * @return the registrationId value
     */
    public String registrationId() {
        return this.registrationId;
    }

    /**
     * Get registration create date time (in UTC).
     *
     * @return the createdDateTimeUtc value
     */
    public DateTime createdDateTimeUtc() {
        return this.createdDateTimeUtc;
    }

    /**
     * Get assigned Azure IoT Hub.
     *
     * @return the assignedHub value
     */
    public String assignedHub() {
        return this.assignedHub;
    }

    /**
     * Get device ID.
     *
     * @return the deviceId value
     */
    public String deviceId() {
        return this.deviceId;
    }

    /**
     * Get enrollment status. Possible values include: 'unassigned', 'assigning', 'assigned', 'failed', 'disabled'.
     *
     * @return the status value
     */
    public String status() {
        return this.status;
    }

    /**
     * Get substatus for 'Assigned' devices. Possible values include - 'initialAssignment': Device has been assigned to an IoT hub for the first time, 'deviceDataMigrated': Device has been assigned to a different IoT hub and its device data was migrated from the previously assigned IoT hub. Device data was removed from the previously assigned IoT hub, 'deviceDataReset':  Device has been assigned to a different IoT hub and its device data was populated from the initial state stored in the enrollment. Device data was removed from the previously assigned IoT hub. Possible values include: 'initialAssignment', 'deviceDataMigrated', 'deviceDataReset'.
     *
     * @return the substatus value
     */
    public String substatus() {
        return this.substatus;
    }

    /**
     * Get error code.
     *
     * @return the errorCode value
     */
    public Integer errorCode() {
        return this.errorCode;
    }

    /**
     * Get error message.
     *
     * @return the errorMessage value
     */
    public String errorMessage() {
        return this.errorMessage;
    }

    /**
     * Get last updated date time (in UTC).
     *
     * @return the lastUpdatedDateTimeUtc value
     */
    public DateTime lastUpdatedDateTimeUtc() {
        return this.lastUpdatedDateTimeUtc;
    }

    /**
     * Get the entity tag associated with the resource.
     *
     * @return the etag value
     */
    public String etag() {
        return this.etag;
    }

}
