/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.sdk.iot.provisioning.service.models;

import org.joda.time.DateTime;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Enrollment group record.
 */
public class EnrollmentGroup {
    /**
     * Enrollment Group ID.
     */
    @JsonProperty(value = "enrollmentGroupId", required = true)
    private String enrollmentGroupId;

    /**
     * Attestation method used by the device.
     */
    @JsonProperty(value = "attestation", required = true)
    private AttestationMechanism attestation;

    /**
     * The Iot Hub host name.
     */
    @JsonProperty(value = "iotHubHostName")
    private String iotHubHostName;

    /**
     * Initial device twin.
     */
    @JsonProperty(value = "initialTwin")
    private InitialTwin initialTwin;

    /**
     * The entity tag associated with the resource.
     */
    @JsonProperty(value = "etag")
    private String etag;

    /**
     * The provisioning status. Possible values include: 'enabled', 'disabled'.
     */
    @JsonProperty(value = "provisioningStatus")
    private String provisioningStatus;

    /**
     * The behavior when a device is re-provisioned to an IoT hub.
     */
    @JsonProperty(value = "reprovisionPolicy")
    private ReprovisionPolicy reprovisionPolicy;

    /**
     * The DateTime this resource was created.
     */
    @JsonProperty(value = "createdDateTimeUtc", access = JsonProperty.Access.WRITE_ONLY)
    private DateTime createdDateTimeUtc;

    /**
     * The DateTime this resource was last updated.
     */
    @JsonProperty(value = "lastUpdatedDateTimeUtc", access = JsonProperty.Access.WRITE_ONLY)
    private DateTime lastUpdatedDateTimeUtc;

    /**
     * The allocation policy of this resource. This policy overrides the tenant
     * level allocation policy for this individual enrollment or enrollment
     * group. Possible values include 'hashed': Linked IoT hubs are equally
     * likely to have devices provisioned to them, 'geoLatency':  Devices are
     * provisioned to an IoT hub with the lowest latency to the device.If
     * multiple linked IoT hubs would provide the same lowest latency, the
     * provisioning service hashes devices across those hubs, 'static' :
     * Specification of the desired IoT hub in the enrollment list takes
     * priority over the service-level allocation policy, 'custom': Devices are
     * provisioned to an IoT hub based on your own custom logic. The
     * provisioning service passes information about the device to the logic,
     * and the logic returns the desired IoT hub as well as the desired initial
     * configuration. We recommend using Azure Functions to host your logic.
     * Possible values include: 'hashed', 'geoLatency', 'static', 'custom'.
     */
    @JsonProperty(value = "allocationPolicy")
    private String allocationPolicy;

    /**
     * The list of names of IoT hubs the device(s) in this resource can be
     * allocated to. Must be a subset of tenant level list of IoT hubs.
     */
    @JsonProperty(value = "iotHubs")
    private List<String> iotHubs;

    /**
     * Custom allocation definition.
     */
    @JsonProperty(value = "customAllocationDefinition")
    private CustomAllocationDefinition customAllocationDefinition;

    /**
     * Get enrollment Group ID.
     *
     * @return the enrollmentGroupId value
     */
    public String enrollmentGroupId() {
        return this.enrollmentGroupId;
    }

    /**
     * Set enrollment Group ID.
     *
     * @param enrollmentGroupId the enrollmentGroupId value to set
     * @return the EnrollmentGroup object itself.
     */
    public EnrollmentGroup withEnrollmentGroupId(String enrollmentGroupId) {
        this.enrollmentGroupId = enrollmentGroupId;
        return this;
    }

    /**
     * Get attestation method used by the device.
     *
     * @return the attestation value
     */
    public AttestationMechanism attestation() {
        return this.attestation;
    }

    /**
     * Set attestation method used by the device.
     *
     * @param attestation the attestation value to set
     * @return the EnrollmentGroup object itself.
     */
    public EnrollmentGroup withAttestation(AttestationMechanism attestation) {
        this.attestation = attestation;
        return this;
    }

    /**
     * Get the Iot Hub host name.
     *
     * @return the iotHubHostName value
     */
    public String iotHubHostName() {
        return this.iotHubHostName;
    }

    /**
     * Set the Iot Hub host name.
     *
     * @param iotHubHostName the iotHubHostName value to set
     * @return the EnrollmentGroup object itself.
     */
    public EnrollmentGroup withIotHubHostName(String iotHubHostName) {
        this.iotHubHostName = iotHubHostName;
        return this;
    }

    /**
     * Get initial device twin.
     *
     * @return the initialTwin value
     */
    public InitialTwin initialTwin() {
        return this.initialTwin;
    }

    /**
     * Set initial device twin.
     *
     * @param initialTwin the initialTwin value to set
     * @return the EnrollmentGroup object itself.
     */
    public EnrollmentGroup withInitialTwin(InitialTwin initialTwin) {
        this.initialTwin = initialTwin;
        return this;
    }

    /**
     * Get the entity tag associated with the resource.
     *
     * @return the etag value
     */
    public String etag() {
        return this.etag;
    }

    /**
     * Set the entity tag associated with the resource.
     *
     * @param etag the etag value to set
     * @return the EnrollmentGroup object itself.
     */
    public EnrollmentGroup withEtag(String etag) {
        this.etag = etag;
        return this;
    }

    /**
     * Get the provisioning status. Possible values include: 'enabled', 'disabled'.
     *
     * @return the provisioningStatus value
     */
    public String provisioningStatus() {
        return this.provisioningStatus;
    }

    /**
     * Set the provisioning status. Possible values include: 'enabled', 'disabled'.
     *
     * @param provisioningStatus the provisioningStatus value to set
     * @return the EnrollmentGroup object itself.
     */
    public EnrollmentGroup withProvisioningStatus(String provisioningStatus) {
        this.provisioningStatus = provisioningStatus;
        return this;
    }

    /**
     * Get the behavior when a device is re-provisioned to an IoT hub.
     *
     * @return the reprovisionPolicy value
     */
    public ReprovisionPolicy reprovisionPolicy() {
        return this.reprovisionPolicy;
    }

    /**
     * Set the behavior when a device is re-provisioned to an IoT hub.
     *
     * @param reprovisionPolicy the reprovisionPolicy value to set
     * @return the EnrollmentGroup object itself.
     */
    public EnrollmentGroup withReprovisionPolicy(ReprovisionPolicy reprovisionPolicy) {
        this.reprovisionPolicy = reprovisionPolicy;
        return this;
    }

    /**
     * Get the DateTime this resource was created.
     *
     * @return the createdDateTimeUtc value
     */
    public DateTime createdDateTimeUtc() {
        return this.createdDateTimeUtc;
    }

    /**
     * Get the DateTime this resource was last updated.
     *
     * @return the lastUpdatedDateTimeUtc value
     */
    public DateTime lastUpdatedDateTimeUtc() {
        return this.lastUpdatedDateTimeUtc;
    }

    /**
     * Get the allocation policy of this resource. This policy overrides the tenant level allocation policy for this individual enrollment or enrollment group. Possible values include 'hashed': Linked IoT hubs are equally likely to have devices provisioned to them, 'geoLatency':  Devices are provisioned to an IoT hub with the lowest latency to the device.If multiple linked IoT hubs would provide the same lowest latency, the provisioning service hashes devices across those hubs, 'static' : Specification of the desired IoT hub in the enrollment list takes priority over the service-level allocation policy, 'custom': Devices are provisioned to an IoT hub based on your own custom logic. The provisioning service passes information about the device to the logic, and the logic returns the desired IoT hub as well as the desired initial configuration. We recommend using Azure Functions to host your logic. Possible values include: 'hashed', 'geoLatency', 'static', 'custom'.
     *
     * @return the allocationPolicy value
     */
    public String allocationPolicy() {
        return this.allocationPolicy;
    }

    /**
     * Set the allocation policy of this resource. This policy overrides the tenant level allocation policy for this individual enrollment or enrollment group. Possible values include 'hashed': Linked IoT hubs are equally likely to have devices provisioned to them, 'geoLatency':  Devices are provisioned to an IoT hub with the lowest latency to the device.If multiple linked IoT hubs would provide the same lowest latency, the provisioning service hashes devices across those hubs, 'static' : Specification of the desired IoT hub in the enrollment list takes priority over the service-level allocation policy, 'custom': Devices are provisioned to an IoT hub based on your own custom logic. The provisioning service passes information about the device to the logic, and the logic returns the desired IoT hub as well as the desired initial configuration. We recommend using Azure Functions to host your logic. Possible values include: 'hashed', 'geoLatency', 'static', 'custom'.
     *
     * @param allocationPolicy the allocationPolicy value to set
     * @return the EnrollmentGroup object itself.
     */
    public EnrollmentGroup withAllocationPolicy(String allocationPolicy) {
        this.allocationPolicy = allocationPolicy;
        return this;
    }

    /**
     * Get the list of names of IoT hubs the device(s) in this resource can be allocated to. Must be a subset of tenant level list of IoT hubs.
     *
     * @return the iotHubs value
     */
    public List<String> iotHubs() {
        return this.iotHubs;
    }

    /**
     * Set the list of names of IoT hubs the device(s) in this resource can be allocated to. Must be a subset of tenant level list of IoT hubs.
     *
     * @param iotHubs the iotHubs value to set
     * @return the EnrollmentGroup object itself.
     */
    public EnrollmentGroup withIotHubs(List<String> iotHubs) {
        this.iotHubs = iotHubs;
        return this;
    }

    /**
     * Get custom allocation definition.
     *
     * @return the customAllocationDefinition value
     */
    public CustomAllocationDefinition customAllocationDefinition() {
        return this.customAllocationDefinition;
    }

    /**
     * Set custom allocation definition.
     *
     * @param customAllocationDefinition the customAllocationDefinition value to set
     * @return the EnrollmentGroup object itself.
     */
    public EnrollmentGroup withCustomAllocationDefinition(CustomAllocationDefinition customAllocationDefinition) {
        this.customAllocationDefinition = customAllocationDefinition;
        return this;
    }

}
