/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.sdk.iot.provisioning.service.models;


/**
 * Current registration status.
 */
public class IndividualEnrollmentRegistrationState extends DeviceRegistrationState {
}
