/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.sdk.iot.provisioning.service.models;

import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Metadata for the TwinCollection.
 */
public class Metadata {
    /**
     * Last time the TwinCollection was updated.
     */
    @JsonProperty(value = "lastUpdated")
    private DateTime lastUpdated;

    /**
     * This SHOULD be null for Reported properties metadata and MUST not be
     * null for Desired properties metadata.
     */
    @JsonProperty(value = "lastUpdatedVersion")
    private Long lastUpdatedVersion;

    /**
     * Get last time the TwinCollection was updated.
     *
     * @return the lastUpdated value
     */
    public DateTime lastUpdated() {
        return this.lastUpdated;
    }

    /**
     * Set last time the TwinCollection was updated.
     *
     * @param lastUpdated the lastUpdated value to set
     * @return the Metadata object itself.
     */
    public Metadata withLastUpdated(DateTime lastUpdated) {
        this.lastUpdated = lastUpdated;
        return this;
    }

    /**
     * Get this SHOULD be null for Reported properties metadata and MUST not be null for Desired properties metadata.
     *
     * @return the lastUpdatedVersion value
     */
    public Long lastUpdatedVersion() {
        return this.lastUpdatedVersion;
    }

    /**
     * Set this SHOULD be null for Reported properties metadata and MUST not be null for Desired properties metadata.
     *
     * @param lastUpdatedVersion the lastUpdatedVersion value to set
     * @return the Metadata object itself.
     */
    public Metadata withLastUpdatedVersion(Long lastUpdatedVersion) {
        this.lastUpdatedVersion = lastUpdatedVersion;
        return this;
    }

}
