// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

/**
 * This package contains the models classes for ProvisioningServiceClient.
 * API for service operations with the Azure IoT Hub Device Provisioning Service.
 */
package com.microsoft.azure.sdk.iot.provisioning.service.models;
