/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.sdk.iot.provisioning.service.models;

import java.util.Map;
import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Contains the properties of an error returned by the Azure IoT Hub
 * Provisioning Service.
 */
public class ProvisioningServiceErrorDetails {
    /**
     * The errorCode property.
     */
    @JsonProperty(value = "errorCode")
    private Integer errorCode;

    /**
     * The trackingId property.
     */
    @JsonProperty(value = "trackingId")
    private String trackingId;

    /**
     * The message property.
     */
    @JsonProperty(value = "message")
    private String message;

    /**
     * The info property.
     */
    @JsonProperty(value = "info")
    private Map<String, String> info;

    /**
     * The timestampUtc property.
     */
    @JsonProperty(value = "timestampUtc")
    private DateTime timestampUtc;

    /**
     * Get the errorCode value.
     *
     * @return the errorCode value
     */
    public Integer errorCode() {
        return this.errorCode;
    }

    /**
     * Set the errorCode value.
     *
     * @param errorCode the errorCode value to set
     * @return the ProvisioningServiceErrorDetails object itself.
     */
    public ProvisioningServiceErrorDetails withErrorCode(Integer errorCode) {
        this.errorCode = errorCode;
        return this;
    }

    /**
     * Get the trackingId value.
     *
     * @return the trackingId value
     */
    public String trackingId() {
        return this.trackingId;
    }

    /**
     * Set the trackingId value.
     *
     * @param trackingId the trackingId value to set
     * @return the ProvisioningServiceErrorDetails object itself.
     */
    public ProvisioningServiceErrorDetails withTrackingId(String trackingId) {
        this.trackingId = trackingId;
        return this;
    }

    /**
     * Get the message value.
     *
     * @return the message value
     */
    public String message() {
        return this.message;
    }

    /**
     * Set the message value.
     *
     * @param message the message value to set
     * @return the ProvisioningServiceErrorDetails object itself.
     */
    public ProvisioningServiceErrorDetails withMessage(String message) {
        this.message = message;
        return this;
    }

    /**
     * Get the info value.
     *
     * @return the info value
     */
    public Map<String, String> info() {
        return this.info;
    }

    /**
     * Set the info value.
     *
     * @param info the info value to set
     * @return the ProvisioningServiceErrorDetails object itself.
     */
    public ProvisioningServiceErrorDetails withInfo(Map<String, String> info) {
        this.info = info;
        return this;
    }

    /**
     * Get the timestampUtc value.
     *
     * @return the timestampUtc value
     */
    public DateTime timestampUtc() {
        return this.timestampUtc;
    }

    /**
     * Set the timestampUtc value.
     *
     * @param timestampUtc the timestampUtc value to set
     * @return the ProvisioningServiceErrorDetails object itself.
     */
    public ProvisioningServiceErrorDetails withTimestampUtc(DateTime timestampUtc) {
        this.timestampUtc = timestampUtc;
        return this;
    }

}
