/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.sdk.iot.provisioning.service.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A Json query request.
 */
public class QuerySpecification {
    /**
     * The query.
     */
    @JsonProperty(value = "query", required = true)
    private String query;

    /**
     * Get the query.
     *
     * @return the query value
     */
    public String query() {
        return this.query;
    }

    /**
     * Set the query.
     *
     * @param query the query value to set
     * @return the QuerySpecification object itself.
     */
    public QuerySpecification withQuery(String query) {
        this.query = query;
        return this;
    }

}
