/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package com.microsoft.azure.sdk.iot.provisioning.service.models;

import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents a collection of properties within a Twin.
 */
public class TwinCollection {
    /**
     * Unmatched properties from the message are deserialized this collection.
     */
    @JsonProperty(value = "")
    private Map<String, Object> additionalProperties;

    /**
     * Version of the TwinCollection.
     */
    @JsonProperty(value = "version")
    private Long version;

    /**
     * Number of properties in the TwinCollection.
     */
    @JsonProperty(value = "count")
    private Integer count;

    /**
     * Metadata for the TwinCollection.
     */
    @JsonProperty(value = "metadata")
    private Metadata metadata;

    /**
     * Get unmatched properties from the message are deserialized this collection.
     *
     * @return the additionalProperties value
     */
    public Map<String, Object> additionalProperties() {
        return this.additionalProperties;
    }

    /**
     * Set unmatched properties from the message are deserialized this collection.
     *
     * @param additionalProperties the additionalProperties value to set
     * @return the TwinCollection object itself.
     */
    public TwinCollection withAdditionalProperties(Map<String, Object> additionalProperties) {
        this.additionalProperties = additionalProperties;
        return this;
    }

    /**
     * Get version of the TwinCollection.
     *
     * @return the version value
     */
    public Long version() {
        return this.version;
    }

    /**
     * Set version of the TwinCollection.
     *
     * @param version the version value to set
     * @return the TwinCollection object itself.
     */
    public TwinCollection withVersion(Long version) {
        this.version = version;
        return this;
    }

    /**
     * Get number of properties in the TwinCollection.
     *
     * @return the count value
     */
    public Integer count() {
        return this.count;
    }

    /**
     * Set number of properties in the TwinCollection.
     *
     * @param count the count value to set
     * @return the TwinCollection object itself.
     */
    public TwinCollection withCount(Integer count) {
        this.count = count;
        return this;
    }

    /**
     * Get metadata for the TwinCollection.
     *
     * @return the metadata value
     */
    public Metadata metadata() {
        return this.metadata;
    }

    /**
     * Set metadata for the TwinCollection.
     *
     * @param metadata the metadata value to set
     * @return the TwinCollection object itself.
     */
    public TwinCollection withMetadata(Metadata metadata) {
        this.metadata = metadata;
        return this;
    }

}
