name: $(BuildID)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

parameters:
- name: branch
  displayName: The branch of the Azure/azure-iot-sdk-csharp repo to package from
  type: string
  default: main
- name: publishHubDevice
  displayName: Publish the 'com.microsoft.azure.sdk.iot:iot-device-client' package
  type: string
  values:
    - true
    - false
  default: false
- name: publishDpsDevice
  displayName: Publish the 'com.microsoft.azure.sdk.iot.provisioning:provisioning-device-client' package
  type: string
  values:
    - true
    - false
  default: false
- name: publishDpsService
  displayName: Publish 'com.microsoft.azure.sdk.iot.provisioning:provisioning-service-client' package
  type: string
  values:
    - true
    - false
  default: false
- name: publishDpsSecurity
  displayName: Publish 'com.microsoft.azure.sdk.iot.provisioning.security:security-provider' package
  type: string
  values:
    - true
    - false
  default: false
- name: publishDpsSecurityX509
  displayName: Publish 'com.microsoft.azure.sdk.iot.provisioning.security:x509-provider' package
  type: string
  values:
    - true
    - false
  default: false
- name: publishDpsSecurityTpm
  displayName: Publish 'com.microsoft.azure.sdk.iot.provisioning.security:tpm-provider' package
  type: string
  values:
    - true
    - false
  default: false

jobs:
  - job: LINUX
    displayName: Linux
    pool:
      vmImage: ubuntu-20.04
    steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: 11
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          mvn clean install -DskipTests -T 2C  --batch-mode -q

    - template: templates/DeleteCloudResources.yaml
      displayName: "Pack IoT hub device client"
      condition: eq(${{ parameters.publishHubDevice }}, 'true')
      parameters:
        - packagePath: '$(Build.SourcesDirectory)/iothub/device/iot-device-client'

    - template: templates/DeleteCloudResources.yaml
      displayName: "Pack DPS device client"
      condition: eq(${{ parameters.publishDpsDevice }}, 'true')
      parameters:
        - packagePath: '$(Build.SourcesDirectory)/provisioning/provisioning-device-client'

    - template: templates/DeleteCloudResources.yaml
      displayName: "Pack DPS service client"
      condition: eq(${{ parameters.publishDpsService }}, 'true')
      parameters:
        - packagePath: '$(Build.SourcesDirectory)/provisioning/provisioning-service-client'

    - template: templates/DeleteCloudResources.yaml
      displayName: "Pack DPS security provider"
      condition: eq(${{ parameters.publishDpsSecurity }}, 'true')
      parameters:
        - packagePath: '$(Build.SourcesDirectory)/provisioning/security/security-provider'

    - template: templates/DeleteCloudResources.yaml
      displayName: "Pack DPS TPM provider"
      condition: eq(${{ parameters.publishDpsSecurityTpm }}, 'true')
      parameters:
        - packagePath: '$(Build.SourcesDirectory)/provisioning/security/tpm-provider'

    - template: templates/DeleteCloudResources.yaml
      displayName: "Pack DPS X509 provider"
      condition: eq(${{ parameters.publishDpsSecurityX509 }}, 'true')
      parameters:
        - packagePath: '$(Build.SourcesDirectory)/provisioning/security/x509-provider'

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'azuresdkpartnerdrops'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az storage blob upload-batch --source "$(Build.SourcesDirectory)/output/" --destination "drops/azure-iot-sdks/java/$(Build.BuildNumber)" --account-name azuresdkpartnerdrops --auth-mode login'
    
    - bash: |
        echo "Files uploaded to partner storage directory drops/azure-iot-sdks/java/$(Build.BuildNumber)"
        echo "Go to https://dev.azure.com/azure-sdk/internal/_build?definitionId=1809&_a=summary and run the pipeline with Relative Path in Partner Drops Blob Container set to azure-iot-operations-sdks/dotnet/$(Build.BuildNumber)"
      displayName: Next Steps
    