package samples.com.microsoft.azure.sdk.iot;

import com.azure.core.credential.AzureSasCredential;
import com.microsoft.azure.sdk.iot.provisioning.service.ProvisioningServiceClient;
import com.microsoft.azure.sdk.iot.provisioning.service.Query;
import com.microsoft.azure.sdk.iot.provisioning.service.configs.*;
import com.microsoft.azure.sdk.iot.provisioning.service.exceptions.ProvisioningServiceClientException;

import java.util.UUID;

public class ProvisioningAzureSasCredentialSample
{
    public static void main (String[] args) throws ProvisioningServiceClientException
    {
        SamplesArguments parsedArguments = new SamplesArguments(args);

        String sharedAccessSignature = parsedArguments.getProvisioningSharedAccessSignature();

        // Shared access signatures can be generated by the SDK for you by using the service client constructor
        // that take in your Provisioning connection string. This sample will demonstrate how to construct service clients
        // without giving them the connection string by giving them shared access signatures instead.

        // This sample's readme includes a helper function that shows how to build shared access signatures below.

        // The AzureSasCredential object supports updating the shared access signature which is important to do
        // once the previous signature has expired, or is close to expiring. This sample assumes that no renewal will
        // be necessary since the sample completes in a few seconds. After updating the credential object, any
        // clients that were constructed with that credential will start using the updated signature

        //String updatedSignature = "some new shared access signature";
        //credential.update(updatedSignature);
        AzureSasCredential azureSasCredential = new AzureSasCredential(sharedAccessSignature);

        ProvisioningServiceClient provisioningServiceClient = new ProvisioningServiceClient(parsedArguments.getDPSHostName(), azureSasCredential);

        runIndividualEnrollmentSample(provisioningServiceClient);

        runEnrollmentGroupSample(provisioningServiceClient);
    }

    private static void runIndividualEnrollmentSample (ProvisioningServiceClient provisioningServiceClient) throws ProvisioningServiceClientException
    {
        // ******************************** Create a new individualEnrollment config **********************************
        String registrationId = "my-new-enrollment-" + UUID.randomUUID();
        Attestation attestation = new SymmetricKeyAttestation("", "");
        IndividualEnrollment individualEnrollment = new IndividualEnrollment(registrationId, attestation);

        // ************************************ Create the individualEnrollment *************************************
        System.out.println("\nAdd new individualEnrollment...");
        IndividualEnrollment individualEnrollmentResult =  provisioningServiceClient.createOrUpdateIndividualEnrollment(individualEnrollment);
        System.out.println("\nIndividualEnrollment created with success...");
        System.out.println(individualEnrollmentResult);

        // ************************************* Get info of individualEnrollment *************************************
        System.out.println("\nGet the individualEnrollment information...");
        IndividualEnrollment getResult = provisioningServiceClient.getIndividualEnrollment(registrationId);
        System.out.println(getResult);

        // ************************************ Query info of individualEnrollment ************************************
        System.out.println("\nCreate a query for enrollments...");
        QuerySpecification querySpecification =
                new QuerySpecificationBuilder("*", QuerySpecificationBuilder.FromType.ENROLLMENTS)
                        .createSqlQuery();
        Query query = provisioningServiceClient.createIndividualEnrollmentQuery(querySpecification);

        while(query.hasNext())
        {
            System.out.println("\nQuery the next enrollments...");
            QueryResult queryResult = query.next();
            System.out.println(queryResult);
        }

        // *********************************** Delete info of individualEnrollment ************************************
        System.out.println("\nDelete the individualEnrollment...");
        provisioningServiceClient.deleteIndividualEnrollment(registrationId);
    }

    private static void runEnrollmentGroupSample (ProvisioningServiceClient provisioningServiceClient) throws ProvisioningServiceClientException
    {
        /*
         * Create the device collection.
         */
        String enrollmentGroupId = "enrollmentgroupid-" + UUID.randomUUID();

        // *************************************** Create a new enrollmentGroup ****************************************
        System.out.println("\nCreate a new enrollmentGroup...");
        Attestation attestation = new SymmetricKeyAttestation("", "");
        EnrollmentGroup enrollmentGroup =
                new EnrollmentGroup(
                        enrollmentGroupId,
                        attestation);
        System.out.println("\nAdd new enrollmentGroup...");
        EnrollmentGroup enrollmentGroupResult =  provisioningServiceClient.createOrUpdateEnrollmentGroup(enrollmentGroup);
        System.out.println("\nEnrollmentGroup created with success...");
        System.out.println(enrollmentGroupResult);

        // **************************************** Get info of enrollmentGroup ****************************************
        System.out.println("\nGet the enrollmentGroup information...");
        EnrollmentGroup getResult = provisioningServiceClient.getEnrollmentGroup(enrollmentGroupId);
        System.out.println(getResult);

        // *************************************** Query info of enrollmentGroup ***************************************
        System.out.println("\nCreate a query for the enrollmentGroups...");
        QuerySpecification querySpecification =
                new QuerySpecificationBuilder("*", QuerySpecificationBuilder.FromType.ENROLLMENT_GROUPS)
                        .createSqlQuery();
        Query query = provisioningServiceClient.createEnrollmentGroupQuery(querySpecification);

        while(query.hasNext())
        {
            System.out.println("\nQuery the next enrollmentGroups...");
            QueryResult queryResult = query.next();
            System.out.println(queryResult);
        }

        // ************************************** Delete info of enrollmentGroup ***************************************
        System.out.println("\nDelete the enrollmentGroup...");
        provisioningServiceClient.deleteEnrollmentGroup(enrollmentGroupId);
    }
}
