name: $(BuildID)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
trigger: none
pr: none
schedules:
  - cron: "30 6 * * *" # every night at 10:30 pm PST (6:30 am UTC)
    displayName: Nightly cleanup
    branches:
      include:
        - hubCleanupSample
    always: true
jobs:
- job: hub_and_dps_cleanup
  timeoutInMinutes: 90
  pool:
    vmImage: windows-latest
  displayName: Windows Cleanup
  condition: succeeded()
  steps:
  - powershell: ./vsts/cleanup.ps1
    displayName: 'Run Cleanup script'
    env:
      COMMIT_FROM: $(COMMIT_FROM)
      IOTHUB_CONNECTION_STRING: $(WINDOWS-IOTHUB-CONNECTION-STRING)
      IOT_DPS_CONNECTION_STRING: $(WINDOWS-IOT-DPS-CONNECTION-STRING)
    condition: always()
  
  # In case the previous run failed due to a maven compilation issue
  - powershell: ./vsts/cleanup.ps1
    displayName: 'Run Cleanup script'
    env:
      COMMIT_FROM: $(COMMIT_FROM)
      IOTHUB_CONNECTION_STRING: $(WINDOWS-IOTHUB-CONNECTION-STRING)
      IOTHUB_CONNECTION_STRING2: $(IOTHUB-CONNECTION-STRING)
      IOT_DPS_CONNECTION_STRING: $(WINDOWS-IOT-DPS-CONNECTION-STRING)
      IOT_DPS_CONNECTION_STRING2: $(IOT-DPS-CONNECTION-STRING)
    condition: always()
