package com.microsoft.azure.sdk.iot.common;

public class TestConstants
{
    public static String IOT_HUB_CONNECTION_STRING_ENV_VAR_NAME = "IOTHUB_CONNECTION_STRING";
    public static String STORAGE_ACCOUNT_CONNECTION_STRING_ENV_VAR_NAME = "STORAGE_ACCOUNT_CONNECTION_STRING";
    public static String UNTRUSTWORTHY_IOT_HUB_CONNECTION_STRING_ENV_VAR_NAME = "IOTHUB_CONN_STRING_INVALIDCERT";
}
